demo:
  entries:
    basic:
      int_value: 0
      long_value: 1
      float_value: 0.2
      double_value: 3.0
      long_slider: 1
      float_slider: 20.0
      volume_slider: 1.0
      string_value: Hello There!
    lists:
      int_list:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 32
    maps:
      instruction_list:
      - move: 2
      - tower: 1
      - rotate: 3
      - move: 2
      - dig: 2
