modLoader="javafml"
loaderVersion="[36,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="simpleconfig"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[[dependencies.simpleconfig]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleconfig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"