modLoader="javafml"
loaderVersion="[41,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="simpleconfig"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[modproperties.simpleconfig]
    catalogueImageIcon="${logo_file}"
[[dependencies.simpleconfig]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleconfig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"