package endorh.simpleconfig.api.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Flag the entry generated by this <b>static</b> field as
 * requiring a restart to be effective<br>
 *
 * This annotation has no effects in backing fields of
 * entries defined in the builder
 *
 * @see Entry
 */
@Target({ElementType.FIELD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface RequireRestart {
	/**
	 * Whether the annotated entry requires a restart to be effective
	 * or not
	 */
	boolean value() default true;
}
