package endorh.simpleconfig.core.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks the entry generated by this field (if any) as non-persistent.<br>
 * Non-persistent entries do not produce an entry in the config file,
 * and are reset on every restart.
 * They're rarely useful to enable debug/profiling features you wouldn't
 * wish to leave on accidentally.
 *
 * @see Entry
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface NonPersistent {}
