# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1,)" # Require at least 1.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="simplekonfig"
version="${file.jarVersion}"
displayName="Simple Konfig Test"
credits=""
authors=""
description='''
Example mod that uses Kotlin for Forge with the Simple Konfig API.
'''
[[dependencies.simplekonfig]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplekonfig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
