plugins {
    `java-library`
    id("net.minecraftforge.gradle")
}

val apiVersion by extra("0.1.5")
val modVersion by extra("0.8.17")
val mappingsChannel by extra("official")
val mappingsVersion by extra("1.16.5")
val mcVersion by extra("1.16.5")
val forge by extra("36.1.0")
val forgeVersion by extra("$mcVersion-$forge")

val modGroup by extra("endorh.simpleconfig")
val modId by extra("simpleconfig")
val vendor by extra("Endor H")

val apiArchiveBaseName by extra("$modId-api")
val modArchiveBaseName by extra("$modId")

val apiMavenArtifact by extra("$modGroup:$modId-api:$apiVersion")
val modMavenArtifact by extra("$modGroup:$modId:$modVersion")

val credits by extra("")
val authors by extra("Endor H")
val issueTracker by extra("")
val page by extra("")
val updateJson by extra("")
val logoFile by extra("${modId}.png")
val modDescription by extra("""
    Provides a simple way for modders to define config files with autogenerated config menus and commands.
    Can also provide, or even replace config menus of other mods.
    
    Users can assign hotkeys to modify config values from within the game, and easily save and apply partial presets, which can be shared on the server.
    To edit server configs, players need to be authorized, or be top level operators.

    Optionally adds a button to the pause menu, which opens the mod list in order to access mod configs in-game . It's also possible to bind a hotkey to open the mod list, edit config hotkeys, or open a specific config menu.
""".trimIndent())

// License
val license by extra("LGPL")

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

println("Java: " + System.getProperty("java.version") + " JVM: " + System.getProperty("java.vm.version") + "(" + System.getProperty("java.vendor") + ") Arch: " + System.getProperty("os.arch"))

minecraft {
    mappings(mappingsChannel, mappingsVersion)
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
}

repositories {
    maven("https://repo.maven.apache.org/maven2") {
        name = "Maven Central"
    }
    maven("https://www.cursemaven.com") {
        name = "Curse Maven" // Curse Maven
        content {
            includeGroup("curse.maven")
        }
    }
}

dependencies {
    implementation("org.jetbrains:annotations:23.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")

    "minecraft"("net.minecraftforge:forge:${forgeVersion}")
}